- name: Install Tools
  hosts: localhost
  connection: local
  become: yes
  vars:
    tools:
    - nginx
    - httpd
  
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop: "{{ tools }}"

  - name: enable nginx
    ansible.builtin.service:
      name: "{{ item }}"
      state: started
      enabled: yes
    loop: "{{ tools }}"
