- name: Install Tools using dict
  hosts: localhost
  connection: local
  vars:
    tools: {
      tool1: nginx
    }

  tasks:
  - name: Installing Tools
    ansible.builtin.package:
      name: "{{ item.value }}"
      state: present
    loop: "{{ tools | dict2items }}"