- name: filters
  hosts: localhost
  connection: local
  vars:
    name_string: "This is TZ"
    skills:
    - Ansible
    - TF
    - Git

    dict_try: {
      tool1: "Ansible",
      tool2: "TF",
      tool3: Git 
    }

  tasks:
  - name: make string upper
    ansible.builtin.debug:
      msg: "{{ name_string | upper }}"

  - name: make string lower
    ansible.builtin.debug:
      msg: "{{ name_string | lower }}"

  - name: List way
    ansible.builtin.debug:
      msg: "{{ skills | join(',') }}"
    
  - name: Dict way
    ansible.builtin.debug:
      msg: "{{ dict_try | to_json }}"
    register: dict_skillset

  - name: Output of dict try
    ansible.builtin.debug:
      msg: "{{ dict_skillset }}"


  