- name: This is try and cache in ansible
  hosts: loclhost
  connection: local
  tasks:
  - block:
      name: Install nginx
      ansible.builtin.package:
        name: nginx
        state: present
    
    rescue:
      - name: Installation Failed
        ansible.builtin.debug:
          msg: "Installation Failed, Please check anf verify"

    always:
      - name: Always run
        absible.builtin.debug:
          msg: "Task Completed"