- name: demo on filters
  hosts: local
  connection: local
  tasks:
  - name: read students yaml
    ansible.builtin.set_fact: # setting the variable
      student_yaml: "{{ lookup('file', 'ubuntufacts.yaml' ) | from_yaml }}"

  - name: convert YAML to JSON
    ansible.builtin.debug:
      msg: "{{ student_yaml | to_nice_json  }}"

