# ==== NOT WORKING ====

- name: Read JSON using slurp and convert to variable
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: read ubuntu facts yaml file
      ansible.builtin.set_fact:
        ubuntu_fact_data: "{{ lookup('file', 'ubuntu-facts.json') | from_json }}"
    
    - name: convert Json to YAML
      ansible.builtin.debug:
        msg: "{{ ubuntu_fact_data | to_nice_yaml }}"