- name: Json to Yaml
  hosts: localhost
  connection: local
  tasks:
    - name: convert ubuntu facts json file to xml
      debug:
        msg: >- 
          {{ 
            lookup('file', 'ubuntu-facts.json')
            | from_json 
            | to_xml(root='ubuntu_facts') 
          }}
      register: ansible_facts_xml

      

    - name: Print ubuntu facts in xml
      debug:
        msg: "{{ ansible_facts_xml }}"